
version: 0.0
os: linux
files:
  - source: /
    destination: /Task-Manager
hooks:
  BeforeInstall:
    - location: scripts/install_components.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
